# Generated by Django 4.1 on 2022-09-14 19:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-deadline', 'time_stamp', 'completed')},
        ),
        migrations.AlterField(
            model_name='collaborators',
            name='users',
            field=models.ManyToManyField(related_name='my_collaborations', to=settings.AUTH_USER_MODEL),
        ),
    ]
