# Generated by Django 4.1 on 2022-09-14 19:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0002_alter_task_options_alter_collaborators_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collaborators',
            new_name='Collaborations',
        ),
    ]
