# Generated by Django 4.1 on 2023-01-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-deadline', 'time_stamp', 'completed')},
        ),
    ]
