# Generated by Django 4.1 on 2023-01-07 14:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0003_alter_task_options_alter_task_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(related_name='collabs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dependencies',
            name='dependent_on',
            field=models.ManyToManyField(blank=True, related_name='dependants', to='task.task'),
        ),
    ]
