# Generated by Django 4.1 on 2023-01-09 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0007_alter_task_collaborators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='collabs', related_query_name='collabs', to=settings.AUTH_USER_MODEL),
        ),
    ]
